dist: bionic
sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    packages: lcov
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

  # Install lcov 1.11
  - wget http://downloads.sourceforge.net/ltp/lcov-1.14.tar.gz
  - tar -xvf lcov-1.14.tar.gz
  - cd lcov-1.14 && sudo make install
  - cd ..
install: 
  - sudo apt-get install -qq g++-8
  - sudo apt-get install -qq gcc-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
script:
  - mkdir debug && cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - ./Json-Utils
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' '*/third-party/*' '*/tests/*' --output-file coverage.info
  - lcov --list coverage.info 
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
