dist: bionic
sudo: required
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - clang-3.8
install:
  - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
script:
  - mkdir debug && cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
