dist: bionic
sudo: false
language: cpp
script:
  - mkdir debug && cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
matrix:
include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env:
      - MATRIX_EVAL="CC=gcc-8 CXX=g++-8"
