dist: bionic
sudo: required
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-bionic-7.0
    packages:
    - clang-7.0
install:
  - "[ $CXX = clang++ ] && export CXX=clang++-7.0 || true"
script:
  - mkdir debug && cd debug
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make
